### ISSUE TITLE
What is the type of CF?

### ISSUE THREAD

**Issue by huyentk** [D-Andreev/recommender-addon#25]
which type does your package use in collaborative filtering, Item-based or User-based?

**Comment by D-Andreev** [comment]
Hey @huyentk 
The collaborative filtering is user-based. The input for it is a table with users ratings for the different items.  For finding similarity of items in a collection you can use the `tf-idf` method.

**Comment by huyentk** [comment]
So if I want to use item-based, where can I change or customize?
Thank you.
